spring:
  application:
    name: ttodo-api
  profiles:
    group:
      dev:
        - "common-dev"
      prod:
        - "common-prod"
    active: dev
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  messages:
    basename: messages
    encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

springdoc:
  swagger-ui:
    path: /
  api-docs:
    path: /v3/api-docs

# 동적 쿼리 시스템 설정
app:
  specification:
    index-advisor:
      enabled: true # 인덱스 추천 기능 활성화
      daily-reset: false # 매일 통계 리셋 여부
    performance:
      slow-query-threshold: 1000 # 느린 쿼리 임계값 (ms)
      log-all-queries: false # 모든 쿼리 로깅 여부

---

spring:
  config:
    activate:
      on-profile: '!prod'
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisReactiveAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
