spring:
  application:
    name: ttodo-api
  profiles:
    group:
      dev:
        - "common-dev"
      prod:
        - "common-prod"
    active: dev
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  messages:
    basename: messages
    encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

springdoc:
  swagger-ui:
    path: /
  api-docs:
    path: /v3/api-docs

---

spring:
  config:
    activate:
      on-profile: '!prod'
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisReactiveAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
