spring:
  application:
    name: ttodo-api
  main:
    lazy-initialization: true  # 빈 지연 로딩으로 시작 속도 향상

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 25  # 배치 처리로 성능 향상
        order_inserts: true
        order_updates: true
        generate_statistics: false  # 통계 생성 비활성화
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  messages:
    basename: messages
    encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# JWT 설정
jwt:
  private-key: classpath:ttodo/jwt/test-private.pem
  public-key: classpath:ttodo/jwt/public.pem
  key-id: rsa-key-id
  access-token:
    expiration: 60
    cookie:
      name: access-token
      path: /
      sameSite: Lax
      secure: false
      httpOnly: false
  refresh-token:
    expiration: 31536000
    cookie:
      name: refresh-token
      path: /
      sameSite: Lax
      secure: false
      httpOnly: true

# CORS 설정
app:
  cors:
    allowed-origins:
      - http://localhost:5173  # Vite development server
      - http://localhost:8080  # Backend API
      - http://localhost:4173  # Vite preview
    allowed-methods:
      - GET
      - POST
      - PUT
      - PATCH
      - DELETE
      - OPTIONS
    allowed-headers:
      - Content-Type
      - Authorization
      - X-Requested-With
      - Accept
      - Origin
    allow-credentials: true
    max-age: 3600
