app:
  scheme: https
  host: api.ttodo.xiyo.dev
  port: 443

jwt:
  private-key: classpath:ttodo/jwt/test-private.pem
  public-key: classpath:ttodo/jwt/public.pem
  key-id: rsa-key-id
  access-token:
    expiration: 60
    cookie:
      name: access-token
      domain: ttodo.xiyo.dev
      path: /
      secure: true
      httpOnly: false
      sameSite: Lax
  refresh-token:
    expiration: 31536000
    cookie:
      name: refresh-token
      domain: ttodo.xiyo.dev
      path: /
      secure: true
      httpOnly: true
      sameSite: Lax

  # CORS 설정
  cors:
    allowed-origins:
      - https://ttodo.xiyo.dev
      - https://api.ttodo.xiyo.dev
    allowed-methods:
      - GET
      - POST
      - PUT
      - PATCH
      - DELETE
      - OPTIONS
    allowed-headers:
      - Content-Type
      - Authorization
      - X-Requested-With
      - Accept
      - Origin
    allow-credentials: true
    max-age: 3600
