# 개발 환경 설정
spring:
  devtools:
    restart:
      enabled: true  # 개발 환경에서는 핫 리로드 활성화
      poll-interval: 2s
      quiet-period: 1s
  jpa:
    show-sql: false  # SQL 로깅 비활성화로 성능 향상
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false

logging:
  level:
    root: info
    point.ttodoApi: info  # debug → info로 변경하여 로깅 오버헤드 감소
    # 필요시 특정 패키지만 debug로 설정
    # point.ttodoApi.auth: debug

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    use-root-path: true